sudo: required


language: node_js

services:
  - docker

node_js:
  - "4.1"
  #- "4.0"
  #- "0.12"

before_install:
 #- node server.js &
  - docker build -t docker_node .
  - docker ps -a
  - docker run -p 3002:3002  docker_node /bin/sh -c "cd /; ./startup_node.sh"

cache: docker_node

install: true
  #- npm install
  #- npm install -g mocha
  #- mocha test

before_script:
   - npm install -g mocha
   - pwd
   - ls -la
   - docker-machine ls
   - curl localhost:3002

script:
   - pwd
   - cd node_server
   - mocha 