sudo: required

language: node_js

services:
  - docker

node_js:
  - "4.1"
  #- "4.0"
  #- "0.12"

before_install:
 #- node server.js &
  - docker build -t docker_node .
  - docker ps -a
  - docker run  docker_node /bin/sh -c "cd /usr/src/node_server;"

install: true
  #- npm install
  #- npm install -g mocha
  #- mocha test

before_script:
   - npm install -g mocha
   - pwd
   - ls -la

script: true
   - pwd
   - mocha 