sudo: required

language: node_js

services:
  - docker

node_js:
  - "4.1"
  - "4.0"
  - "0.12"

before_install:
 #- node server.js &
  - docker build -t docker_node .
  - docker run -d -p 127.0.0.1:3001:3001 docker_node /bin/sh -c "node /usr/src/node_server/server.js"

install:
  #- npm install
  - npm install -g mocha
  #- mocha test

script: true
  #- mocha /usr/src/node_server/test.js